### ISSUE TITLE
php-cli image is missing `patch` package

### ISSUE THREAD

**Issue by vishnuhd** [srijanone/docker-base-images#4]
Debian's `patch` package needs to be installed in the base image to make the composer install workflow work.

Current Issue :
```
- Applying patches for drupal/feeds
    https://www.drupal.org/files/issues/2020-01-15/<patch-url>.patch (feeds-tmp-file-remove)
   **Could not apply patch! Skipping. The error was: Cannot apply patch** https://www.drupal.org/files/issues/2020-01-15/<patch-url>.patch
```

Solution :
```
RUN apt-get update && apt-get install patch
```
This will add `patch` package in the image, to make the composer install succeed.

I can raise a PR for the issue.

**Comment by AshishThakur** [comment]
@WSMathias is this valid or https://github.com/srijanone/docker-base-images/pull/17 fixes this?

**Comment by WSMathias** [comment]
#17 already fixed it 
@vishnuhd  try pulling cli image again

**Comment by WSMathias** [comment]
always use --pull argument while building docker images.
This way you can always have latest build of the same tag as we are continuously fixing bugs.
