### ISSUE TITLE
Fully functional blackfire integration

### ISSUE THREAD

**Issue by AshishThakur** [srijanone/docker-base-images#5]

**Comment by sharmaamitt16** [comment]
@AshishThakur  Added PR for Blackfire integration. Please review.

**docker base images**: https://github.com/srijanone/docker-base-images/pull/26
**vega**: https://github.com/srijanone/vega/pull/72

**Comment by sharmaamitt16** [comment]
Closing the issue as PR is merged and the feature is functional.
