### ISSUE TITLE
[Enhancement]: Anchore Scanner for all base image

### ISSUE THREAD

**Issue by AshishThakur** [srijanone/docker-base-images#6]
* Clone https://github.com/srijanone/docker-base-images
* Check https://github.com/srijanone/docker-base-images/blob/dev/.github/workflows/anchore.yml
* Add Anchore Scanning for all images

**Comment by sharmaamitt16** [comment]
Please review the PR.

**Comment by AshishThakur** [comment]
https://github.com/srijanone/docker-base-images/pull/22 closed.
